タイムラインの切り替え機能の実装
Progate/tweet_app_for_path_intern_B_team pull request #18
Opened 2023-08-27 08:29 UTC by ardRiriy

# Objective and links

- Objective
タイムラインの切り替え機能の実装
- Asana Task URL: https://app.asana.com/0/1205215227306587/1205306348240327/f

## What was changed

HTMLとCSSを書きました．aタグでURL遷移する形で切り替えています．

## What was not changed

## Deploy dependencies

## QA

### local

### staging

## Review deadline

## Others

2023-08-27 08:50 UTC, a-neko requested changes
機能面はよいとおもいます！
ただ、figmaのデザインと比べて文字が太すぎる気がするのでそこをもう少し寄せていけば良いと思います。また、矢印が文字に比べて小さすぎると思うのでspanを用いてそこの大きさだけ大きくしたりアイコンを使ってみたらさらに良くなると思います。

2023-08-30 06:35 UTC, ardRiriy commented
修正しました．確認お願いします

2023-08-30 07:41 UTC, darallium commented
矢印が中心からずれているように見えるので，a.to-postsのdisplayをflexにしてalign-itemをcenterにしておくほうがいいような気がします

2023-08-30 07:47 UTC, darallium commented
それっぽそうな矢印を見つけたので貼ってみます

<span class="material-icons">
arrow_forward
</span>

2023-08-30 10:09 UTC, darallium requested changes
タイトル(tweet app)のリンクがまだpostsのままなので修正する必要があります．

2023-08-30 13:23 UTC, ardRiriy commented
もうちょい詳しく教えてください どこの話ですか？
このPRはあくまでタイムラインの切り替えとそれに付随するフロントの作成なので、関係ないところであれば別のタスクを切ってやってほしいです。

2023-08-30 13:54 UTC, ardRiriy commented
なんとなく理解したので修正入れました．ついでにURL周りも仕様に合うように直しておきましたので確認してください．

2023-08-30 15:16 UTC, darallium approved these changes
良いと思います

2023-08-30 15:18 UTC, merged